
    	<div id="left">
        	<div class="category">
            	<h1>Danh sách category</h1>
                <ul>
                    <?php
                        foreach($categoryAll as $value){
                    ?>
                    <li><a href="<?php echo createUrl('frontend', 'category','index') . "&id=".$value['cate_id']?>">
                        <?php echo $value['cate_name'];?>
                    </a></li>
                    <?php
                        }
                    ?>
                </ul>
            </div>
            
            <div class="category" id="online">
            	<h1>Quảng cáo</h1>
                <img src="<?php echo BASE_URL.'/'.FRONTEND_IMAGES; ?>/doitac.jpg" width="198" />
                <hr />
                <img src="<?php echo BASE_URL.'/'.FRONTEND_IMAGES; ?>/suntech.jpg" width="198" />
            </div>
            
        </div>
    <div id="center">