</div>
        <div id="right">
        	<div class="category">
            	<h1>Danh Giỏ hàng của bạn</h1>
               	<p><a href="#">Tổng số sản phẩm: <span id="total-cart-number"><?php if(isset($_SESSION['totalCart']['number'])) echo $_SESSION['totalCart']['number']; else echo '0'; ?></span></a></p>
                <p><a href="#">Tổng giá tiền: <span id="total-cart-price"><?php if(isset($_SESSION['totalCart']['pro_price'])) echo $_SESSION['totalCart']['pro_price']; else echo '0'; ?></span></a></p>
                <p><a href="<?php echo createUrl('frontend', 'cart', 'viewCart'); ?>">Xem giỏ hàng</a></p>
	            </ul>
            </div>
            <div class="category" id="news">
            	<h1>Danh sách tin tức</h1>
               	<ul id="ulnew">
                	<li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
					<li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
					<li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ </a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ </a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ </a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
					<li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
					<li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ </a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ </a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ </a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                    <li><a href="#" style="font-weight:normal;">Trung tâm hành chính 1.400 tỷ</a></li>
                </ul>
            </div>
        </div>
    </div>