<div id="main">
    	<div id="left">
        	<div class="category">
            	<h1>MENU CHỨC NĂNG</h1>
                <ul>
                    <li><a href="<?php echo createUrl('admin', 'user','index');?>">Quản lý thành viên</a></li>
                    <li><a href="<?php echo createUrl('admin', 'category','index');?>">Quản lý category</a></li>
                    <li><a href="<?php echo createUrl('admin', 'product','index');?>">Quản lý sản phẩm</a></li>
	            </ul>
            </div>
            <div class="category" style="margin-top:10px; border-top:1px solid #CCC; background:#FFF;">
            	<p>Chào bạn: admin</p>
                <p><a href="<?php echo createUrl('admin', 'login','logout');?>">Đăng xuất tài khoản</a></p>
            </div>
        </div>
    <div id="center">