<?php
if(sizeof($product) < 1){
    echo 'Không có sản phẩm nào';
}
else{
    echo '<ul>';
    foreach ($product as $value){
?>

    <li style="margin-left:10px;">
        <h3><a href=""><?php echo $value['product_name'];?></a></h3>
        <img src="<?php echo FRONTEND_IMAGES; ?>/<?php echo $value['product_images'];?>" class="product" />
        <p>Đơn giá: <?php echo $value['product_price'];?></p>
        <a href="#" class="cart"><img src="<?php echo FRONTEND_IMAGES; ?>/giohang.jpg" />Đặt hàng</a>
    </li>
    <?php
    }//end for
}//end ifelse
    echo '</ul>';
?>

        
    