<h1>Danh sách thành viên</h1>
<div id="control">
    <a href="#">Delete Record</a>
    <a href="<?php echo createUrl('admin', 'user','insertUser');?>">Insert</a>
</div>
<table width="700" border="1" cellpadding="0" cellspacing="0" id="list" style="clear:both;">
    <tr>
        <td class="header">ID</td>
        <td class="header">Tên thành viên</td>
        <td class="header">Email</td>
        <td class="header">Address</td> 
        <td class="header">Phone</td>
        <td class="header">Level</td> 
        <td class="header">Edit</td>
        <td class="header">Delete</td>                                                                                            
    </tr>
    <?php
        foreach ($listUser as $value){
    ?>
    <tr>
        <td><?php echo $value['id'];?></td>
        <td><?php echo $value['username'];?></td>
        <td><?php echo $value['email'];?></td>
        <td><?php echo $value['address'];?></td>
        <td><?php echo $value['phone'];?></td>  
        <td><?php echo $value['level'] == '1' ? 'Admin' : 'Member';?></td>  
        <td><a href="<?php echo createUrl('admin', 'user','editUser');?>&id=<?php echo $value['id'];?>">Edit</a></td>
        <td><a href="<?php echo createUrl('admin', 'user','deleteUser');?>&id=<?php echo $value['id'];?>">Delete</a></td>
    </tr>
    <?php 
        }
    ?>

</table>
