<div style="clear:both;"></div>
<?php 
//$validation = new Validation;
?>            
<!-- Form elements -->    
<div class="grid_12">
    <div class="module">
        <h2><span>Insert User</span></h2>
        <div class="module-body">
            <form action="" method="POST">
                <p>
                    <label>Level</label>
                    <select class="input-short" name="level">
                        <option value="">--Chọn quyền--</option>
                        <option value="1"<?php echo $validation->setBox('level','1','selected') ?>>Member</option>
                        <option value="2"<?php echo $validation->setBox('level','2','selected') ?>>Administrator</option>
                    </select>
                    <span class="error">
                    <?php
                        echo $validation->getError('level');
                    ?>
                    </span>
                </p>
                
                <p>
                    <label>User name</label>
                    <input type="text" class="input-short" name="name" size="250" value='<?php echo $validation->getParam('name');?>'/>
                    <span class="error">
                    <?php
                        echo $validation->getError('name');
                    ?>
                    </span>
                </p>
                            
                <p>
                    <label>Password</label>
                    <input type="password" class="input-short" name="password"/>
                    <span class="error">
                    <?php
                        echo $validation->getError('password');
                    ?>
                    </span>
                </p>
                            
                <p>
                    <label>Re-password</label>
                    <input type="password" class="input-short" name="re-password"/>
                    <span class="error">
                    <?php
                        echo $validation->getError('repassword');
                    ?>
                    </span>
                </p>
                   
                <p>
                    <label>Email</label>
                    <input type="text" class="input-short" name="email" size="250" value='<?php echo $validation->getParam('email');?>'/>
                    <span class="error">
                    <?php
                        echo $validation->getError('email');
                    ?>
                    </span>
                </p>
                
                <p>
                    <label>Address</label>
                    <input type="text" class="input-short" name="address" size="250" value='<?php echo $validation->getParam('address');?>'/>
                    <span class="error">
                    <?php
                        echo $validation->getError('address');
                    ?>
                    </span>
                </p>
                
                <p>
                    <label>Phone</label>
                    <input type="text" class="input-short" name="phone" size="250" value='<?php echo $validation->getParam('phone');?>'/>
                    <span class="error">
                    <?php
                        echo $validation->getError('phone');
                    ?>
                    </span>
                </p>      
                   
                <fieldset>
                    <input class="submit-green" type="submit" value="Submit" name="submit"/> 
                    <input class="submit-gray" type="reset" value="Reset" />
                </fieldset>
            </form>
        </div> <!-- End .module-body -->

    </div>  <!-- End .module -->
    <div style="clear:both;"></div>
</div> <!-- End .grid_12 -->