<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Login</title>
<style>
    *{
        margin: 0px;
        padding: 0px;
    }
    #wrapper{
        padding: 10px;
        background: #fbfbfb;
        border: 1px solid #ccc;
        width: 400px;
        margin: 100px auto;
    }
    label{
        float: left;
        width: 80px;
    }
    input{
        margin-bottom: 5px;
        padding: 3px;
    }
</style>
</head>
<body>
    <div id="wrapper">
        <form action="" method="post">
            <label>Username</label>
            <input type="text" name="username" value="" />
            <br />
            <label>Password</label>
            <input type="text" name="password" value="" />
            <br />
            <label>&nbsp;</label>
            <input type="submit" name="submit" value="Login" class="btn"/>
        </form>
    </div>
</body>
</html>
