<div style="clear:both;"></div>            

<!-- Form elements -->    
<div class="grid_12">
    <div class="module">
        <h2><span>Edit User</span></h2>
        <div class="module-body">
            <form action="" method="POST">
                <p>
                    <label>Level</label>
                    <select class="input-short" name="level">
                        <option value="">Chọn </option>
                        <option value="2" <?php echo $validation->setBox('level', '2', 'selected'); ?>>Member</option>
                        <option value="1" <?php echo $validation->setBox('level', '1', 'selected'); ?>>Administrator</option>
                    </select>
                    <span class="error">
                    <?php 
                        echo $validation->getError('level');
                    ?>
                        </span>
                </p>
                
                <p>
                    <label>User name</label>
                    <input type="text" class="input-short" name="name" value="<?php echo $validation->getParam('name');?>" size="250"/>
                    <span class="error">
                    <?php 
                        echo $validation->getError('name');
                    ?>
                        </span>
                </p>
                            
                <p>
                    <label>Password</label>
                    <input type="password" class="input-short" name="password"/>
                    <span class="error">
                    <?php 
                        echo $validation->getError('password');
                    ?>
                        </span>
                </p>
                            
                <p>
                    <label>Re-password</label>
                    <input type="password" class="input-short" name="repassword"/>
                    <span class="error">
                    <?php
                        echo $validation->getError('repassword');
                    ?>
                        </span>
                </p>
                   
                <p>
                    <label>Email</label>
                    <input type="text" class="input-short" name="email" value="<?php echo $validation->getParam('email');;?>" size="250"/>
                    <span class="error">
                    <?php 
                        echo $validation->getError('email');
                    ?>
                        </span>
                </p>
                
                <p>
                    <label>Address</label>
                    <input type="text" class="input-short" name="address" value="<?php echo $validation->getParam('address');?>" size="250"/>
                    <span class="error">
                    <?php 
                        echo $validation->getError('address');
                    ?>
                        </span>
                </p>
                
                <p>
                    <label>Phone</label>
                    <input type="text" class="input-short" name="phone" value="<?php echo $validation->getParam('phone');?>" size="250"/>
                    <span class="error">
                    <?php 
                        echo $validation->getError('phone');
                    ?>
                        </span>
                </p>      
                   
                <p>
                    <label>Gender</label>
                    Nam &nbsp;<input type="radio" name="gender" value="1" <?php echo $validation->setBox('gender','1'); ?>/>
                    Nữ &nbsp;<input type="radio" name="gender" value="2" <?php echo $validation->setBox('gender','2'); ?>/>
                    <span class="error">
                    <?php
                        echo $validation->getError('gender');
                    ?>
                    </span>
                </p>
                <fieldset>
                    <input class="submit-green" type="submit" value="Submit" name="submit"/> 
                    <input class="submit-gray" type="reset" value="Reset" />
                </fieldset>
            </form>
        </div> <!-- End .module-body -->

    </div>  <!-- End .module -->
    <div style="clear:both;"></div>
</div> <!-- End .grid_12 -->