
    	<div id="left">
        	<div class="category">
            	<h1>Danh sách sản phẩm</h1>
                <ul>
                    <li><a href="#">Menu item 1</a></li>
                    <li><a href="#">Menu item 2</a></li>
                    <li><a href="#">Menu item 3</a></li>
                    <li><a href="#">Menu item 4</a></li>
                    <li><a href="#">Menu item 5</a></li>
                    <li><a href="#">Menu item 6</a></li>
                    <li><a href="#">Menu item 7</a></li>
                    <li><a href="#">Menu item 8</a></li>
                    <li><a href="#">Menu item 9</a></li>
                    <li><a href="#">Menu item 10</a></li>
	            </ul>
            </div>
            
            <div class="category" id="online">
            	<h1>Quảng cáo</h1>
                <img src="<?php echo FRONTEND_IMAGES; ?>/doitac.jpg" width="198" />
                <hr />
                <img src="<?php echo FRONTEND_IMAGES; ?>/suntech.jpg" width="198" />
            </div>
            
        </div>
    <div id="center">